// recipe.json is authoritative. Every value is represented, including extensions.
const list = (values) => values.length ? values.map((v) => `- ${v}`).join('\n') : 'None.';
const json = (value) => {
  const body = JSON.stringify(value, null, 2);
  const fence = '`'.repeat(Math.max(3, ...[...body.matchAll(/`+/g)].map((m) => m[0].length + 1)));
  return `${fence}json\n${body}\n${fence}`;
};

export function renderRecipe(recipe) {
  if (!recipe || typeof recipe !== 'object' || Array.isArray(recipe)) throw new Error('recipe must be an object');
  for (const key of ['slug', 'version', 'status', 'domain', 'path', 'title', 'guidance']) {
    if (typeof recipe[key] !== 'string' || !recipe[key].trim()) throw new Error(`missing ${key}`);
  }
  for (const key of ['slug', 'version', 'status', 'domain', 'path']) {
    if (!/^[a-zA-Z0-9_./-]+$/.test(recipe[key])) throw new Error(`unsafe frontmatter value: ${key}`);
  }
  const d = recipe.description;
  if (!d || ['need', 'input', 'core_action', 'output'].some((k) => typeof d[k] !== 'string')) throw new Error('invalid description');
  for (const key of ['activities', 'outcomes', 'use_cases', 'connector_types']) {
    if (!Array.isArray(recipe[key])) throw new Error(`invalid ${key}`);
  }
  const lines = ['---', `name: ${recipe.slug}`, `version: ${recipe.version}`, `status: ${recipe.status}`,
    `domain: ${recipe.domain}`, `path: ${recipe.path}`, '---', '',
    '<!-- Generated by scripts/render-recipes.mjs. Edit recipe.json, then regenerate. -->', '',
    `# ${recipe.title}`, '',
    `**Need.** ${d.need}`, '', `**Input.** ${d.input}`, '',
    `**Core action.** ${d.core_action}`, '', `**Output.** ${d.output}`, '',
    '## Activities', '',
    ...recipe.activities.map((a, i) => `${i + 1}. ${a.label} *(${a.kind}; ${a.id})*`), '',
    '## Outcomes', ''];
  for (const o of recipe.outcomes) {
    if (!Array.isArray(o.success_criteria)) throw new Error(`invalid success criteria: ${o.id}`);
    lines.push(`### ${o.id}`, '', o.statement, '', list(o.success_criteria), '');
  }
  lines.push('## Guidance', '', recipe.guidance, '', '## Where this is worth adopting', '',
    list(recipe.use_cases), '', '## Connector types', '', list(recipe.connector_types), '',
    '## Recommended trigger', '', json(recipe.recommended_trigger ?? null), '');
  // Preserve every remaining field rather than discarding unfamiliar schema extensions.
  const shown = new Set(['slug', 'version', 'status', 'domain', 'path', 'title', 'description',
    'activities', 'outcomes', 'guidance', 'use_cases', 'connector_types', 'recommended_trigger']);
  const details = Object.fromEntries(Object.entries(recipe).filter(([key]) => !shown.has(key)));
  // Nested extension fields also remain visible, even if prose only uses known fields.
  const extensions = {};
  for (const [key, known] of Object.entries({ description: ['need','input','core_action','output'],
    activities: ['id','label','kind'], outcomes: ['id','statement','success_criteria'] })) {
    const values = Array.isArray(recipe[key]) ? recipe[key] : [recipe[key]];
    if (values.some((v) => Object.keys(v).some((k) => !known.includes(k)))) extensions[key] = recipe[key];
  }
  lines.push('## Adoption details and provenance', '', json(details), '');
  if (Object.keys(extensions).length) lines.push('## Extended fields', '', json(extensions), '');
  return lines.join('\n');
}
